### ISSUE TITLE
Feature request: Sort by instance

### ISSUE THREAD

**Issue by Jordo76** [mnao305/VRCFriendCheck#1]
Hello, 

I really love using this extension and you did a magnificent job at it! I noticed you updated it today and I was wondering if I could sneak in a feature request.
A feature similar to the one found on http://snep.pw/friends/ where friends in the same instance are regrouped, in your app it could just be they're shown one after the other or another way would be to have friends occupy the same cell leading to only one dropdown menu instead of 3?

Thank you very much for this extension and keep up the good job!

**Comment by mnao305** [comment]
Hello! @Jordo76 
Thank you for sending us a feature request!

I confirmed the service of that URL.
Currently the user's display is not sorted in particular, but I will change it to sort by instance ID and I will try to make it easy to understand that I am in the same instance.

Also, it is a specification that only one pulldown can not be displayed. Modify it so that it can be set to open more than one.

I use Google Translate to translate from English to Japanese and from Japanese to English. If you think that the meaning is wrong it would be great if you reply!

**Comment by Jordo76** [comment]
Hi!
Thank you for considering this, I have to say I'm very excited to see that feature come to life. The translation has a few weird parts but it's completely understandable nonetheless, have a good day!

**Comment by mnao305** [comment]
Hi!

Updated the application to version 0.7.0! Try updating the application!
This makes it possible to sort by instance ID. It can be changed from options.

https://github.com/mnao305/VRCFriendCheck/releases/tag/0.7.0
